config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'appointments/new'
  root "doctors#index"


  resources :doctors
  resources :patients do
    resources :appointments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end
# f.datetime_local_field

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :doctors, through: :appointments

    def full_name
        "#{self.first_name} #{self.last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.create(doctor_params)
    
    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to doctor_path
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :specialty)
    end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :update, :edit, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create(patient_params)
    if @patient.save
      redirect_to @patient
    else 
      render :new
    end
  end

  def edit
  end


  def update
    if @patient.update(patient_params)
      redirect_to patients_path
    else
      render :edit
    end
  end


  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private

    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name)
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/doctors/index.html.erb
<h1>List of Doctors and Their Specialty</h1>
<%= link_to 'Add Doctor', new_doctor_path %>
<h2><%= @doctors.length <= 0 ? "Not a Doctor" : "" %></h2>
<ul>
    <% @doctors.each do |doctor| %>
        <li>
            <%= link_to doctor.name, doctor %>
            <%= doctor.specialty %>
        </li>
    <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add New Doctor</h1>
<%= form_with(model:@doctor, local: true, class: "ui form") do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>
    </div>

    <div class="field">
        <%= f.label :specialty %>
        <%= f.text_field :specialty, required: true, autofocus: true, placeholder: "Specialty"%>
    </div>
    <%= f.submit nil, class: "ui inverted pink button" %>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<h1>The Doctor Appointment App</h1>
<div class="ui secondary vertical pointing menu">
    <%= link_to 'Doctors', doctors_path %> |
    <%= link_to 'Add Doctor', new_doctor_path %> |
    <%= link_to 'Patients', patients_path %> |
    <%= link_to 'Add Patient', new_patient_path %> |
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorAppointment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="ui container">
    <%= yield %>
      </div>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients</h1>
<%= link_to 'Add Patient Name', new_patient_path %>
<hr />
<ul>
    <% @patients.each do |patient| %>
        <li>
            <%= link_to patient.full_name, patient %>
        </li>
<% end %>
</ul>

app/views/patients/new.html.erb
<h1>Add Patient Info</h1>
<%= form_with(model:@patient, local: true, class: "ui form") do |f| %>
    <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, require: true, autofocus: true, placeholder: "First Name" %>
    </div>
    <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, require: true, autofocus: true, placeholder: "Last Name" %>
    </div>
    <%= f.submit nil, class: "ui yellow button inverted" %>
<% end %>

 

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>
<hr />
<h3>Doctors</h3>
<ul> 
    <%= @patient.doctors.each do |doctor| %>
        <li>
            <%= link_to doctor.name, doctor %>
            <%= doctor.specialty %>
        </li>
  
    <% end %>
</ul>
<br />
<br />
<br />
<br />
<%= link_to 'Delete Patient', @patient, method: :delete, class: "ui orange button inverted" %>